#ifndef ACTUATORVALUESPARSERSTEP_HPP
#define ACTUATORVALUESPARSERSTEP_HPP

#include "ArduMY.hpp"

enum ActuatorValuesParserStep: uint8_t {

	ENABLED_ACTUATOR_BITS, ACTUATOR_VALUE_BATCHES, END_OF_OP

};


#endif // ACTUATORVALUESPARSERSTEP_HPP
