#ifndef ACTUATORCONFIGPARSERSTEP_HPP
#define ACTUATORCONFIGPARSERSTEP_HPP

enum ActuatorConfigParserStep: uint8_t {

	FLAGS, TYPE, REPRESENTATION, NICK, GEAR_NUMERATOR, GEAR_DENOMINATOR, POSITION_FEEDBACK, TACHOMETER, ENCODER_PIN_A, ENCODER_PIN_B, ENCODER_DEBOUNCE, LIMIT_SWITCH_PIN_START, LIMIT_SWITCH_PIN_END, LIMIT_SWITCH_DEBOUNCE, STEP_PHASE_COUNT, STEP_STEPS_PER_ROTATION, RC_SERVO_PIN, RANGE_START, RANGE_SPAN, END_OF_OPERATION

};

#endif // ACTUATORCONFIGPARSERSTEP_HPP
