#ifndef ACTUATORVALUEREPRESENTATION_HPP
#define ACTUATORVALUEREPRESENTATION_HPP

enum ActuatorValueRepresentation: uint8_t {
	BIT
	, BYTE
	, WORD
	, DOUBLE_WORD
	, QUAD_WORD
	, SINGLE_FLOAT
	, DOUBLE_FLOAT
	, REPRESENTATION_COUNT
};


#endif // ACTUATORVALUEREPRESENTATION_HPP
