#ifndef ARDUMYACTUATORVALUEREPRESENTATION_HPP
#define ARDUMYACTUATORVALUEREPRESENTATION_HPP

#include "ArduMY.hpp"

enum ArduMYActuatorValueRepresentation: uint8_t {
	BIT
	, BYTE
	, WORD
	, DOUBLE_WORD
	, QUAD_WORD
	, SINGLE_FLOAT
	, DOUBLE_FLOAT
	, REPRESENTATION_COUNT
};


#endif // ARDUMYACTUATORVALUEREPRESENTATION_HPP
