# Inspiration from http://stackoverflow.com/questions/29721240/ci-for-qt-app-build-with-different-qt-versions
# Inspiration from http://stackoverflow.com/questions/22111549/travis-ci-with-clang-3-4-and-c11
# Inspiration from https://jonasw.de/blog/2015/07/22/develop/cplusplus14-on-travis-with-cmake/
# Inspiration from http://apt.llvm.org/

language: cpp
compiler: gcc
os:
  - linux
#  - osx
dist: trusty
env:
  global:
    - QT_VERSION_MAJOR=5
    # xenial still not out in 2017 !1!!?
    - TRAVIS_DIST_NAME=trusty
    - CLANG_VERSION=4.0
  matrix:
#    - QT_VERSION_MINOR=6 QT_VERSION_REVISION=2
    - QT_VERSION_MINOR=8 QT_VERSION_REVISION=0
#    - QT_VERSION_MINOR=9 QT_VERSION_REVISION=0

# Avoid sudo to speed up things a little
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-5
      - gcc-5

addons:
  apt:
    sources:
      - llvm-toolchain-trusty-4.0
    packages:
      - clang-4.0

addons:
  apt:
    sources:
      - sourceline: 'ppa:beineri/opt-qt58-trusty'
      - sourceline: 'deb http://ppa.launchpad.net/beineri/opt-qt58-trusty/ubuntu trusty main'
      - key_url: 'http://keyserver.ubuntu.com:11371/pks/lookup?op=get&search=0x10C56D0DE9977759'
    packages:
      - qt58-meta-full
    

before_install:
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew update;
    fi
         
install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-5" CC="gcc-5"; fi
  - if [ "$CXX" = "clang++" ]; then export CXX="clang++-${CLANG_VERSION}" CC="clang-${CLANG_VERSION}"; fi
#  - if [ "$CXX" == "g++" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi
  - if [ "$CXX" == "clang++" ]; then cwd=$(pwd); fi
  - if [ "$TRAVIS_OS_NAME" = "osx" ]; then 
      brew install qt${QT_VERSION_MAJOR}${QT_VERSION_MINOR};
      brew link --force qt${QT_VERSION_MAJOR}${QT_VERSION_MINOR};
    fi
#  - sudo chmod +x scripts/prep.sh  - sudo scripts/prep.sh

before_script:
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then export QT_ENV_SCRIPT="/opt/qt${QT_VERSION_MAJOR}${QT_VERSION_MINOR}/bin/qt${QT_VERSION_MAJOR}${QT_VERSION_MINOR}-env.sh"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then echo "QT_ENV_SCRIPT=${QT_ENV_SCRIPT}"; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then cat ${QT_ENV_SCRIPT}; fi
  - if [ "$TRAVIS_OS_NAME" = "linux" ]; then source ${QT_ENV_SCRIPT}; fi


script:
  - OCOMY_BUILD_ROOT=build
  - mkdir -p ${OCOMY_BUILD_ROOT}
  - cd ${OCOMY_BUILD_ROOT}
  - touch ../local_overrides.pri
  - pwd
  - which c++
  - c++ --version
  - which qmake
  - qmake -v
  - qmake ../OctoMY.pro
  - make -j 2 -l


notifications:
  email:
    recipients:
      - lennartrolland@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "irc.freenode.net:8001#octomy"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"


