install:
  - sudo apt-get update
  - sudo apt-get install qt5-default qtbase5-dev qt5-qmake qtbase5-dev-tools build-essential
  - sudo scripts/prep.sh

script:
  - mkdir build
  - cd build
  - qmake -project
  - qmake ../OctoMY.pro
  - make


notifications:
  email:
    recipients:
      - lennartrolland@gmail.com
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#octomy"
    on_success: change
    on_failure: always
    template:
      - "%{repository} (%{commit}) : %{message} %{foo} "
      - "Build details: %{build_url}"
