#ifndef UNBOXINGSTAGE_HPP
#define UNBOXINGSTAGE_HPP

#include <QString>

enum UnboxingStage{
	  UNKNOWN_STAGE
	, CONTROLLER_CONFIGURATION_STAGE
	, CONTROLLER_TYPE_STAGE
	, DELIVERY_STAGE
	, PAIRING_STAGE
	, SERIAL_DEVICE_STAGE
	, ARDUMY_DEVICE_STAGE
	, HANDOVER_STAGE
	, UNBOXING_COMPLETE
};

QString UnboxingStageToSTring(UnboxingStage s);

#endif // UNBOXINGSTAGE_HPP
