ARG debtest_base=qt5.10.0_static_ubuntu_amd64.octomy.deb:latest
FROM "$debtest_base" as build

MAINTAINER Lennart Rolland <lennartrolland@gmail.com>

FROM    ubuntu:16.04

RUN     apt-get -y update && \
		apt-get -y upgrade && \
		apt-get install -y x11vnc xvfb net-tools

#mkdir ~/.vnc
#		x11vnc -storepasswd 1234 ~/.vnc/passwd

ENV		DEB_DIR /root/deb

WORKDIR	/tmp
ENV		debfile=octomy-agent.deb
COPY	--from=build  $DEB_DIR/$debfile .
RUN		apt install --no-install-recommends -y ./$debfile


# Install Xvfb init script
ADD xvfb_init /etc/init.d/xvfb
RUN chmod a+x /etc/init.d/xvfb

ADD x11vnc_init /etc/init.d/x11vnc
RUN chmod a+x /etc/init.d/x11vnc

ADD xvfb-run  /usr/bin/xvfb-run
RUN chmod a+x /usr/bin/xvfb-run

ENTRYPOINT	/usr/bin/xvfb-run /usr/local/bin/agent

