#ifndef COMMSSESSIONIDTYPE_HPP
#define COMMSSESSIONIDTYPE_HPP

#include <QtGlobal>

typedef quint16 SESSION_ID_TYPE;

typedef quint32 SESSION_NONCE_TYPE;

#define INVALID_SESSION_ID (0)

#define INVALID_NONCE (0)

#endif // COMMSSESSIONIDTYPE_HPP
