DEFINES += USE_DOCS
DEFINES += USE_TESTS_BASIC
DEFINES += USE_TESTS_WEB
#DEFINES += USE_TESTS_STRESS
#DEFINES += USE_TESTS_SELECTED
#DEFINES += USE_GEAR_DYNAMICS
#DEFINES += USE_QT3D
#DEFINES += EXTERNAL_LIB_ESPEAK
#DEFINES += EXTERNAL_LIB_OPENCV
#DEFINES += EXTERNAL_LIB_OPENCL
#DEFINES += USE_ARDUINO
#DEFINES += USE_STATUS

# Reduce build output to only warnings/errors
CONFIG += silent

