
# Do not optimize by default
QMAKE_CXXFLAGS -= -O
QMAKE_CXXFLAGS -= -O2
QMAKE_CXXFLAGS -= -O3

# Optimize for size in release
release{
	QMAKE_CXXFLAGS += -Os
}
else{
	QMAKE_CXXFLAGS += -g
}

QMAKE_CXXFLAGS_RELEASE -= -O
QMAKE_CXXFLAGS_RELEASE -= -O2
QMAKE_CXXFLAGS_RELEASE -= -O3
QMAKE_CXXFLAGS_DEBUG -= -O
QMAKE_CXXFLAGS_DEBUG -= -O2
QMAKE_CXXFLAGS_DEBUG -= -O3

QMAKE_CXXFLAGS_RELEASE += -Os
QMAKE_CXXFLAGS_DEBUG+= -g

QMAKE_LFLAGS += $$QMAKE_CXXFLAGS
