
AUDIO_IN_DIR =		$$TOP_PWD/libs/libaudio
AUDIO_OUT_DIR =		$$TOP_BUILD/libs/libaudio
LIBS +=				-L$$AUDIO_OUT_DIR -laudio
INCLUDEPATH +=		$$AUDIO_IN_DIR
DEPENDPATH +=		$$AUDIO_IN_DIR
PRE_TARGETDEPS +=	$$AUDIO_OUT_DIR/libaudio.a
