#ifndef ACTUATORCONFIGPARSERSTEP_HPP
#define ACTUATORCONFIGPARSERSTEP_HPP

#include "ardumy_arduino/ArduMY.hpp"


enum ArduMYActuatorConfigParserStep: uint8_t {

	FLAGS=0
	, TYPE//1
	, REPRESENTATION//2
	, NICK//3
	, GEAR_NUMERATOR//4
	, GEAR_DENOMINATOR//5
	, POSITION_FEEDBACK//6
	, TACHOMETER//7
	, ENCODER_PIN_A//8
	, ENCODER_PIN_B//9
	, ENCODER_DEBOUNCE//10
	, LIMIT_SWITCH_PIN_START//11
	, LIMIT_SWITCH_PIN_END//12
	, LIMIT_SWITCH_DEBOUNCE//13
	, STEP_PHASE_COUNT//14
	, STEP_STEPS_PER_ROTATION//15
	, RC_SERVO_PIN//16
	, RANGE_START//17
	, RANGE_SPAN//18
	, END_OF_OPERATION//19

};

#endif // ACTUATORCONFIGPARSERSTEP_HPP
