#ifndef ARDUMYACTUATORVALUEREPRESENTATION_HPP
#define ARDUMYACTUATORVALUEREPRESENTATION_HPP

#include "ardumy_arduino/ArduMY.hpp"

enum ArduMYActuatorValueRepresentation: uint8_t {
    VALREP_BIT
    , VALREP_BYTE
    , VALREP_WORD
    , VALREP_DOUBLE_WORD
    , VALREP_QUAD_WORD
    , VALREP_SINGLE_FLOAT
    , VALREP_DOUBLE_FLOAT
    , VALREP_REPRESENTATION_COUNT
};


#endif // ARDUMYACTUATORVALUEREPRESENTATION_HPP
